// Generated by scripts/generate-elevenlabs-segments.mjs

export const VIDEO_DURATION_IN_FRAMES = 3858;

export const voiceTimeline = [
  {
    "id": "intro",
    "audioPath": "videos/voice-segments/01-intro.mp3",
    "startFrame": 0,
    "durationFrames": 328,
    "audioStartFrame": 12,
    "audioDurationFrames": 278,
    "durationSeconds": 9.25
  },
  {
    "id": "dashboard",
    "audioPath": "videos/voice-segments/02-dashboard.mp3",
    "startFrame": 328,
    "durationFrames": 239,
    "audioStartFrame": 336,
    "audioDurationFrames": 193,
    "durationSeconds": 6.43
  },
  {
    "id": "pos",
    "audioPath": "videos/voice-segments/03-pos.mp3",
    "startFrame": 567,
    "durationFrames": 281,
    "audioStartFrame": 575,
    "audioDurationFrames": 235,
    "durationSeconds": 7.81
  },
  {
    "id": "sales",
    "audioPath": "videos/voice-segments/04-sales.mp3",
    "startFrame": 848,
    "durationFrames": 268,
    "audioStartFrame": 856,
    "audioDurationFrames": 222,
    "durationSeconds": 7.39
  },
  {
    "id": "cash",
    "audioPath": "videos/voice-segments/05-cash.mp3",
    "startFrame": 1116,
    "durationFrames": 218,
    "audioStartFrame": 1124,
    "audioDurationFrames": 172,
    "durationSeconds": 5.72
  },
  {
    "id": "returns",
    "audioPath": "videos/voice-segments/06-returns.mp3",
    "startFrame": 1334,
    "durationFrames": 360,
    "audioStartFrame": 1342,
    "audioDurationFrames": 314,
    "durationSeconds": 10.45
  },
  {
    "id": "stock",
    "audioPath": "videos/voice-segments/07-stock.mp3",
    "startFrame": 1694,
    "durationFrames": 184,
    "audioStartFrame": 1702,
    "audioDurationFrames": 138,
    "durationSeconds": 4.6
  },
  {
    "id": "movements",
    "audioPath": "videos/voice-segments/08-movements.mp3",
    "startFrame": 1878,
    "durationFrames": 254,
    "audioStartFrame": 1886,
    "audioDurationFrames": 208,
    "durationSeconds": 6.92
  },
  {
    "id": "catalog",
    "audioPath": "videos/voice-segments/09-catalog.mp3",
    "startFrame": 2132,
    "durationFrames": 232,
    "audioStartFrame": 2140,
    "audioDurationFrames": 186,
    "durationSeconds": 6.19
  },
  {
    "id": "clients",
    "audioPath": "videos/voice-segments/10-clients.mp3",
    "startFrame": 2364,
    "durationFrames": 228,
    "audioStartFrame": 2372,
    "audioDurationFrames": 182,
    "durationSeconds": 6.03
  },
  {
    "id": "credit",
    "audioPath": "videos/voice-segments/11-credit.mp3",
    "startFrame": 2592,
    "durationFrames": 206,
    "audioStartFrame": 2600,
    "audioDurationFrames": 160,
    "durationSeconds": 5.33
  },
  {
    "id": "map",
    "audioPath": "videos/voice-segments/12-map.mp3",
    "startFrame": 2798,
    "durationFrames": 201,
    "audioStartFrame": 2806,
    "audioDurationFrames": 155,
    "durationSeconds": 5.15
  },
  {
    "id": "reports",
    "audioPath": "videos/voice-segments/13-reports.mp3",
    "startFrame": 2999,
    "durationFrames": 304,
    "audioStartFrame": 3007,
    "audioDurationFrames": 258,
    "durationSeconds": 8.59
  },
  {
    "id": "admin",
    "audioPath": "videos/voice-segments/14-admin.mp3",
    "startFrame": 3303,
    "durationFrames": 242,
    "audioStartFrame": 3311,
    "audioDurationFrames": 196,
    "durationSeconds": 6.53
  },
  {
    "id": "ending",
    "audioPath": "videos/voice-segments/15-ending.mp3",
    "startFrame": 3545,
    "durationFrames": 313,
    "audioStartFrame": 3553,
    "audioDurationFrames": 237,
    "durationSeconds": 7.89
  }
] as const;
