-- ============================================================================
-- peek_sale_number_seq() — read last_value of sale_number_seq without advancing
-- ============================================================================
-- /api/sales/next-number used to read the latest sale and add 1, which races
-- with concurrent inserts and could crash one of two simultaneous POS sales.
--
-- The actual sale number is generated by `generate_sale_number()` (which
-- calls nextval). For UI preview we only need to *peek* at the next value,
-- without burning a number.
-- ============================================================================

SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION public.peek_sale_number_seq()
RETURNS BIGINT
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  -- pg_sequences.last_value is the last value handed out by nextval.
  -- If the sequence has never been called, last_value is the start (1).
  SELECT COALESCE(last_value, 0) FROM public.sale_number_seq;
$$;

COMMENT ON FUNCTION public.peek_sale_number_seq() IS
  'Returns the last value emitted by sale_number_seq without advancing it. Used by /api/sales/next-number for read-only UI preview.';

GRANT EXECUTE ON FUNCTION public.peek_sale_number_seq() TO authenticated;
